---

# This tasks run _only_, when ansible runs against _backup_server_. I.e. there
# is _no_ `delegate_to` here!
- block:
    - name: backup_server | (local) Ensure local public keys directory exists
      file:
        path: "{{ ssh_pubkeys_dir }}"
        state: directory
      delegate_to: localhost

      # FIXME: Requires ansible 2.8.
      #    - name: Generate backup server ssh keypair
      #      openssh_keypair:
      #        path:   '/root/.ssh/id_rsa'
      #        state:  present

    - name: backup_server | Obtain backup server user ssh public keys
      synchronize:
        mode: pull
        src: "{{ ansible_user_dir + '/.ssh/id_rsa.pub' }}"
        dest: "{{ ssh_pubkeys_dir }}"

