---

- block:
    - name: count | Stat file count cache file
      stat:
        path: "{{ r_files_count_cache_file }}"
      register: r_files_count_cache_stats

    - name: count | Stat size cache file
      stat:
        path: "{{ r_size_cache_file }}"
      register: r_size_cache_stats

  delegate_to: localhost
  tags:
    - count_files_cache

- block:
    - name: count | Load file count cache
      include_vars:
        file: "{{ r_files_count_cache_file }}"
        name: r_files_count_cache
      when: r_files_count_cache_stats.stat.exists

    - name: count | Load size cache
      include_vars:
        file: "{{ r_size_cache_file }}"
        name: r_size_cache
      when: r_size_cache_stats.stat.exists

    - name: count | Loaded file count cache
      debug:
        var: r_files_count_cache
    - name: count | Loaded size cache
      debug:
        var: r_size_cache

  tags:
    - count_files_cache

- block:
    - name: count | Stat backup points
      stat:
        path: "{{ r_snapshot_root + '/' + item }}"
      loop: >-
        {{  ( ['daily']   | product([0, 1, 2])  | list
            + ['weekly']  | product([0])        | list
            + ['monthly'] | product([0])        | list
            ) | map('join', '.') | list
            + ['.sync']
        }}
      register: r_interval_stats_list
      delegate_to: "{{ backup_server }}"

    - name: Rebuild to dict
      set_fact:
        r_interval_stats: >-
          {{ r_interval_stats_list.results | items2dict(key_name='item', value_name='stat') }}

    - name: count | Determine count interval
      set_fact:
        r_count_interval: >-
          {{ 'daily.1' if r_interval_stats['daily.1'].exists
                else 'daily.0' if r_interval_stats['daily.0'].exists
                else '.sync' if r_interval_stats['.sync'].exists
                else ''
          }}

  when: r_count_files

- block:
    # FIXME: I assume here, that name is unique!
    # For regular backup points `dst` must be specified. For backup scripts
    # `dst` is assumed to be equal to name.
    - name: count | Count files in backups
      shell: >-
        {{ 'set -o pipefail; /usr/bin/find '
              + ( r_snapshot_root + '/' + r_count_interval + '/' + item.dst | default(item.name) )
                | quote
              + '| wc -l' }}
      args:
        executable: '/bin/bash'
      register: r_files_count_raw
      when: r_files_count_cache[item.name] is not defined
      loop: "{{ r_backups + r_backup_scripts }}"
      #changed_when: false

    - name: count | Count size of backups
      command: >-
        {{  '/usr/bin/du -s -b '
              + ( r_snapshot_root + '/' + r_count_interval + '/' + item.dst | default(item.name) )
                | quote
        }}
      register: r_size_raw
      when: r_size_cache[item.name] is not defined
      loop: "{{ r_backups + r_backup_scripts }}"
      #changed_when: false

  delegate_to: "{{ backup_server }}"
  when: r_count_files and r_count_interval != ''

- block:
    - name: count | Rebuild file count to dictionary
      set_fact:
        r_files_count: >-
          {{ r_files_count | combine(
                { item.0.name :
                    r_files_count_cache[item.0.name] | default(
                      item.1.stdout | default(0) | int)
                })
          }}
      loop: >-
        {{ ( r_backups + r_backup_scripts ) | zip(r_files_count_raw.results) | list }}

    - name: count | Rebuild size to dictionary
      set_fact:
        r_size: >-
          {{ r_size | combine(
                { item.0.name :
                    r_size_cache[item.0.name] | default(
                        item.1.stdout | default("0") | regex_search('^[0-9]+(?=\t)') | int
                      )
                })
          }}
      loop: >-
        {{ ( r_backups + r_backup_scripts ) | zip(r_size_raw.results) | list }}

