---

- block:
    - name: define | Define internal r_backups dictionary
      set_fact:
        r_backups2: >-
          {{ r_backups2 + [item.0 | combine(
              { 'full_dst': item.0.dst + '/'
              , 'alias'   : item.0.dst | replace('/', '_')
              , 'full_src':
                  ansible_user_id + '@' + inventory_hostname + ':'
                  + ( item.0.src if item.0.src == '/' else item.0.src + '/././' )
              , 'file_count': item.1.stdout | int
              , 'size'      : item.2.stdout | regex_search('^[0-9]+(?=\t)') | int
              })]
          }}
      loop: >-
        {{ r_backups
            | zip(r_backups_file_count.results, r_backups_size.results)
            | list
        }}

    - name: define | Define internal r_backup_scripts dictionary
      set_fact:
        r_backup_scripts2: >-
          {{ r_backup_scripts2 + [item.0 | combine(
              { 'dst'     : item.0.name
              , 'alias'   : item.0.name | replace('/', '_')
              , 'user'    : item.0.user     | default(db_user) + '-' + item.0.name
              , 'password': item.0.password | default(db_password)
              , 'install' : rsync_filters_dir + '/'
                              + inventory_hostname + '-' + item.0.name
                              + item.0.script | splitext | last
              , 'file_count': item.1.stdout | int
              , 'size'      : item.2.stdout | regex_search('^[0-9]+(?=\t)') | int
              })]
          }}
      loop: >-
        {{ r_backup_scripts
            | zip(r_backup_scripts_file_count.results, r_backup_scripts_size.results)
            | list
        }}

    - name: define | Backup points
      debug:
        var: r_backups2
    - name: define | Backup scripts
      debug:
        var: r_backup_scripts2

    - name: define | Define MySQL scripts dictionary
      set_fact:
        r_backup_scripts_mysql: >-
          {{ r_backup_scripts_mysql + [ item | combine(
              { 'conf'              : role_path + '/templates/mysql.cnf'
              , 'install_conf'      : item.install | splitext | first + '.cnf'
              })]
          }}
      when: item.script == role_path + '/files/mysql.sh'
      loop: "{{ r_backup_scripts2 }}"

    - name: define | Define PostgreSQL scripts dictionary
      set_fact:
        r_backup_scripts_pgsql: >-
          {{ r_backup_scripts_pgsql + [ item | combine(
              { 'conf'              : role_path + '/templates/pgsql.cnf'
              , 'install_conf'      : item.install | splitext | first + '.cnf'
              , 'passfile'          : role_path + '/templates/pgsql.pgpass'
              , 'install_passfile'  : item.install | splitext | first + '.pgpass'
              })]
          }}
      when: item.script == role_path + '/files/pgsql.sh'
      loop: "{{ r_backup_scripts2 }}"

    - name: define | MySQL backup scripts
      debug:
        var: r_backup_scripts_mysql
    - name: define | PostgreSQL backup scripts
      debug:
        var: r_backup_scripts_pgsql

