---
# tasks file for bh-backups

- block:
    - name: Gather facts about host
      gather_facts:
      tags:
        - always

    - name: Gather facts about backup server
      gather_facts:
      delegate_to: "{{ backup_server }}"
      delegate_facts: true
      tags:
        - always

    - name: Count files and size in backups
      import_tasks: 'tasks/count.yml'
      tags:
        - always
        - count_files

    - name: Define internal variables
      import_tasks: tasks/define.yml
      tags:
        - always

    - name: Include ssh setup tasks
      import_tasks: tasks/ssh.yml
      tags:
        - 'rsnapshot_ssh'

    - name: Include database setup tasks
      import_tasks: tasks/db.yml
      tags:
        - 'rsnapshot_db'

    - name: Include rsnapshot setup tasks
      import_tasks: tasks/rsnapshot.yml
      tags:
        - 'rsnapshot'

  when: inventory_hostname in groups['backups']

- block:
    - name: Include backup server setup tasks
      import_tasks: tasks/backup_server.yml

  when: inventory_hostname in groups['backup_servers']
  tags:
    - backup_server

