---
# tasks file for bh-backups

- block:
    - name: Include rsnapshot setup tasks
      import_tasks: tasks/rsnapshot.yml
      tags:
        - 'rsnapshot'

    - name: Include ssh setup tasks
      import_tasks: tasks/ssh.yml
      tags:
        - 'rsnapshot_ssh'

  when: inventory_hostname in groups['backups']
  tags:
    - backups

- block:
    - name: Include backup server setup tasks
      import_tasks: tasks/backup_server.yml

  when: inventory_hostname in groups['backup_servers']
  tags:
    - backup_server

