---
# tasks file for bh-backups

- block:
    - name: Gather facts about backup server
      setup:
      delegate_to: "{{ backup_server }}"
      delegate_facts: true
      tags:
        - always

    - name: Include rsnapshot setup tasks
      import_tasks: tasks/rsnapshot.yml
      tags:
        - 'rsnapshot'

    - name: Include ssh setup tasks
      import_tasks: tasks/ssh.yml
      tags:
        - 'rsnapshot_ssh'

    - name: Include database setup tasks
      import_tasks: tasks/db.yml
      tags:
        - 'rsnapshot_db'

  when: inventory_hostname in groups['backups']

- block:
    - name: Include backup server setup tasks
      import_tasks: tasks/backup_server.yml

  when: inventory_hostname in groups['backup_servers']
  tags:
    - backup_server

