---
# tasks file for bh-backups

- block:
    # FIXME: Remove this. It's not our business.. That should be fixed in play
    # instead.
    - name: Gather facts about host
      gather_facts:

    - name: Gather facts about backup server
      gather_facts:
      delegate_to: "{{ backup_server }}"
      delegate_facts: true

    - name: Determine python version
      set_fact:
        is_python3_used: >-
          {{ hostvars[item].ansible_python.version.major | int == 3 }}
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: >-
        {{ [backup_server, inventory_hostname] }}

    - name: Show detected python versions
      debug:
        msg: "{{ hostvars[item].is_python3_used }}"
      loop: >-
        {{ [backup_server, inventory_hostname] }}

    - name: Define variables
      import_tasks: tasks/define.yml

  tags:
    - always

- block:
    - name: Include backup server setup tasks
      import_tasks: tasks/server.yml
      tags:
        - backup_server

    - name: Count files and size in backups
      import_tasks: 'tasks/count.yml'
      tags:
        - backup_count_files
        - backup_rsnapshot
        - backup_rsnapshot_config
        - backup_db

    - name: Include ssh setup tasks
      import_tasks: tasks/ssh.yml
      tags:
        - backup_ssh

    - name: Include database setup tasks
      import_tasks: tasks/db.yml
      tags:
        - backup_db

    - name: Include rsnapshot setup tasks
      import_tasks: tasks/rsnapshot.yml
      tags:
        - backup_rsnapshot

    - name: Include cron setup tasks
      import_tasks: tasks/cron.yml
      tags:
        - backup_cron

  when: inventory_hostname in groups['backups']

