---
# tasks file for bh-backups

- block:
    - name: Include rsnapshot setup tasks
      import_tasks: tasks/rsnapshot.yml

    - name: Include ssh setup tasks
      import_tasks: tasks/ssh.yml

  when: inventory_hostname in groups['backups']

- block:
    - name: Include backup server setup tasks
      import_tasks: tasks/backup_server.yml

  when: inventory_hostname in groups['backup_servers']

