---
# tasks file for bh-backups

- name: Gather facts about backup server
  setup:
  delegate_to: "{{ backup_server }}"
  delegate_facts: true
  tags:
    - always

- block:
    - name: Include rsnapshot setup tasks
      import_tasks: tasks/rsnapshot.yml
      tags:
        - 'rsnapshot'

    - name: Include ssh setup tasks
      import_tasks: tasks/ssh.yml
      tags:
        - 'rsnapshot_ssh'

  when: inventory_hostname in groups['backups']

- block:
    - name: Include backup server setup tasks
      import_tasks: tasks/backup_server.yml

  when: inventory_hostname in groups['backup_servers']
  tags:
    - backup_server

