---

- block:
    - name: rsnapshot | Add rsnapshot.conf to templates list
      set_fact:
        r_data_templates: >
          {{  [ { 'src'   : role_path + '/templates/rsnapshot.conf'
                , 'dest'  : rsnapshot_conf
                , 'mode'  : '0755'
                , 'force' : true
                }
              ] + r_data_templates }}

      tags:
        - backup_rsnapshot_config
        - backup_db

    - name: rsnapshot | Add rsync filter files to template list
      set_fact:
        r_data_templates: >
          {{  [ { 'src' : item.rsync_filter
                , 'dest': item.install
                , 'mode'  : '0755'
                , 'force' : true
                }
              ] + r_data_templates }}
      loop: "{{ _backup_points }}"
      tags:
        - backup_rsnapshot_filters

    - name: rsnapshot | Add backup script files to file list
      set_fact:
        r_data_files: >
          {{  [ { 'src' : item.script
                , 'dest': item.install
                , 'mode'  : '0755'
                , 'force' : true
                }
              ] + r_data_files }}
      loop: "{{ _backup_scripts }}"
      tags:
        - backup_db

- block:
    - name: rsnapshot | (server) Ensure snapshot root directory exists
      file:
        mode: '0700'
        owner: 'root'
        group: 'root'
        path:  "{{ r_snapshot_root }}"
        state: directory
      tags:
        - backup_rsnapshot_config
        - backup_rsnapshot_filters
        - backup_db

    - name: rsnapshot | (server) Ensure rsync filters directories exist
      file:
        dest:   "{{ item }}"
        owner:  root
        group:  root
        mode:   0755
        state:  directory
      loop:
        - "{{ rsync_filters_dir }}"
        - "{{ rsync_filters_libdir }}"
      tags:
        - backup_rsnapshot_filters

    - name: rsnapshot | (server) Copy rsync filters library files
      copy:
        src:    "{{ item }}"
        dest:   "{{ rsync_filters_libdir }}"
        force:  yes
        backup: yes
      with_fileglob:
        - "rsnapshot.d/lib/*"
      tags:
        - backup_rsnapshot_filters

  delegate_to: "{{ backup_server }}"

- block:
    - name: rsnapshot | (server) Restore or create config files
      include_role:
        name: sgf-restore
        apply:
          tags:
            - always
      vars:
        backup_dir: "{{ backup_root_dir + '/bh-backups' }}"
        default_data_files: "{{ r_data_files }}"
        default_data_templates: "{{ r_data_templates }}"
        default_file_dest: 'huy'
      when: run_mode != 'uninstall'

    - name: rsnapshot | (server) Or delete config files
      file:
        name: "{{ item['dest'] }}"
        state: absent
      loop: "{{ r_data_files + r_data_templates }}"
      when: run_mode == 'uninstall'

  delegate_to: "{{ backup_server }}"
  tags:
    - backup_rsnapshot_config
    - backup_rsnapshot_filters
    - backup_db

# FIXME: Move cron tasks to separate file.
- block:
    - name: rsnapshot | (server) Create cron job for sync and daily
      cron:
        name: "{{ host_id }} sync and daily"
        hour  : "{{ r_sync.hour }}"
        minute: "{{ r_sync.minute }}"

        job: >-
          /usr/bin/rsnapshot -c {{ rsnapshot_conf }} sync ;
          /usr/bin/rsnapshot -c {{ rsnapshot_conf }} daily
        state: present
        user: 'root'
        cron_file: "{{ rsnapshot_cron_file }}"

    - name: rsnapshot | (server) Create cron job for weekly
      cron:
        name: "{{ host_id }} weekly"
        hour  : "{{ r_weekly.hour }}"
        minute: "{{ r_weekly.minute }}"
        weekday: "0"
        job: >-
          /usr/bin/rsnapshot -c {{ rsnapshot_conf }} weekly
        state: present
        user: 'root'
        cron_file: "{{ rsnapshot_cron_file }}"

    - name: rsnapshot | (server) Create cron job for monthly
      cron:
        name: "{{ host_id }} monthly"
        hour  : "{{ r_monthly.hour }}"
        minute: "{{ r_monthly.minute }}"
        day: "1"
        job: >-
          /usr/bin/rsnapshot -c {{ rsnapshot_conf }} monthly
        state: present
        user: 'root'
        cron_file: "{{ rsnapshot_cron_file }}"

  when: run_mode != 'uninstall'
  delegate_to: "{{ backup_server }}"
  tags:
    - backup_cron
    - backup_rsnapshot_config

- name: rsnapshot | (server) Or delete cron jobs
  file:
    name: "{{ rsnapshot_cron_file }}"
    state: absent
  when: run_mode == 'uninstall'
  delegate_to: "{{ backup_server }}"
  tags:
    - backup_cron
    - backup_rsnapshot_config
