---

- block:
    - name: server | (local) Ensure directory for public key exists
      file:
        path: "{{ server_ssh_pubkeys_dir }}"
        state: directory
      delegate_to: localhost

    - name: server | (server) Generate ssh keypair
      openssh_keypair:
        path: "{{ ansible_user_dir + '/.ssh/id_rsa' }}"
        mode: 0600
        comment: "{{ ansible_user_id + '@' + hostvars[backup_server]['ansible_facts']['hostname'] }}"
        regenerate: never
        state:  present

    - name: server | (server) Obtain ssh public key
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir + '/.ssh/id_rsa.pub' }}"
        dest: "{{ server_ssh_pubkeys_dir + '/' }}"
        flat: yes

  delegate_to: "{{ backup_server }}"
  tags:
    - backup_ssh
    - backup_ssh_access

- block:
    - name: server | (server) Install rsnapshot
      package:
        name: "{{ rsnapshot_pkgs }}"
        state: 'present'

    - block:
        - name: server | (server) Add Debian Stretch repository to Debian Jessie
          apt_repository:
            repo: 'deb http://mirror.yandex.ru/debian/ stretch main'
            filename: 'stretch'
            state: present

        - name: server | (server) Lower Debian Stretch priority
          copy:
            src:  'apt-preferences/10stretch'
            dest: '/etc/apt/preferences.d/10stretch'

        - name: server | (server) Install rsnapshot from Debian Stretch
          apt:
            name: rsnapshot=1.4.2-1
            state: present

      when: ansible_distribution == "Debian" and ansible_distribution_major_version | int == 8

  delegate_to: "{{ backup_server }}"
