---

- block:
    - name: server | (local) Ensure local public keys directory exists
      file:
        path: "{{ ssh_pubkeys_dir }}"
        state: directory
      delegate_to: localhost

    - name: server | (backup server) Generate ssh keypair
      openssh_keypair:
        path: "{{ ansible_user_dir + '/.ssh/id_rsa' }}"
        mode: 0600
        regenerate: never
        state:  present

    - name: server | (local) Obtain ssh public key
      synchronize:
        mode: pull
        src: "{{ ansible_user_dir + '/.ssh/id_rsa.pub' }}"
        dest: "{{ ssh_pubkeys_dir }}"

- block:
    - name: server | (backup server) Install rsnapshot
      package:
        name: "{{ rsnapshot_pkgs }}"
        state: 'present'

    - block:
        - name: server | (backup server) Add Debian Stretch repository to Debian Jessie
          apt_repository:
            repo: 'deb http://mirror.yandex.ru/debian/ stretch main'
            filename: 'stretch'
            state: present

        - name: server | (backup server) Lower Debian Stretch priority
          copy:
            src:  'apt-preferences/10stretch'
            dest: '/etc/apt/preferences.d/10stretch'

        - name: server | (backup server) Install rsnapshot from Debian Stretch
          apt:
            name: rsnapshot=1.4.2-1
            state: present

      when: ansible_distribution == "Debian" and ansible_distribution_major_version | int == 8

  delegate_to: "{{ backup_server }}"
